dimensions:
  - name: city
    behavior:
      !<Fixed>
      probability: 0.8
      values: 10
  - name: country
    behavior:
      !<Appear>
      probability: 0.8
      behaviorDelay: 500
      settlingDelay: 1000
      values: 2
  - name: task
    behavior:
      !<Disappear>
      probability: 0.8
      behaviorDelay: 500
      settlingDelay: 1000
      values: 5
  - name: goal
    behavior:
      !<Appear>
      probability: 0.8
      behaviorDelay: 500
      settlingDelay: 1000
      values: 10
  - name: status
    behavior:
      !<Fixed>
      probability: 1
      values: 5
measures:
    - name: Speed
      mean: 50
      stdDev: 0.1
      behavior:
        !<Fixed>
        probability: 0.9
    - name: batteryLevel
      stdDev: 0.1
      mean: 100
      behavior:
        !<Fixed>
        probability: 0.9
frequency: 100
duration: 10000000
hierarchies:
  - [country, city]
  - [goal, task]
  - [status, task]